apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks
  region: us-east-1
  version: "1.27"

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 3
    minSize: 2
    maxSize: 5
    volumeSize: 20

iam:
  withOIDC: true

addons:
  - name: aws-ebs-csi-driver
